//
//  PostModels.swift
//  cleanSwiftProject
//
//  Created by camilo andres ibarra yepes on 27/10/19.
//  Copyright (c) 2019 camilo andres ibarra yepes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostScene
{
  // MARK: Use cases
  
  enum Load
  {
    struct Request
    {
    }
    struct Response {
        let posts: [Post]
    }
    struct ViewModel {
        let posts: [Post]
    }
  }
}
