//
//  PostInteractor.swift
//  cleanSwiftProject
//
//  Created by camilo andres ibarra yepes on 27/10/19.
//  Copyright (c) 2019 camilo andres ibarra yepes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostBusinessLogic
{
  func doLoadInitialData(request: PostScene.Load.Request)
}

protocol PostDataStore
{
  //var name: String { get set }
}

class PostInteractor: PostBusinessLogic, PostDataStore
{
  var presenter: PostPresentationLogic?
  var worker: PostWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doLoadInitialData(request: PostScene.Load.Request)
  {
    worker = PostWorker()
    worker?.fetchPosts(completionHandler: { posts in
        let response = PostScene.Load.Response(posts: posts)
        self.presenter?.presentInitialData(response: response)
    })
  }
}
